export const RANDOMGRAPH_FIELD_LIST_REQUEST = "RANDOMGRAPH_FIELD_LIST_REQUEST";
export const RANDOMGRAPH_FIELD_LIST_SUCCESS = "RANDOMGRAPH_FIELD_LIST_SUCCESS";
export const RANDOMGRAPH_FIELD_LIST_FAIL = "RANDOMGRAPH_FIELD_LIST_FAIL";

export const RANDOMGRAPH_EXCEL_LIST_REQUEST = "RANDOMGRAPH_EXCEL_LIST_REQUEST";
export const RANDOMGRAPH_EXCEL_LIST_SUCCESS = "RANDOMGRAPH_EXCEL_LIST_SUCCESS";
export const RANDOMGRAPH_EXCEL_LIST_FAIL = "RANDOMGRAPH_EXCEL_LIST_FAIL";
